server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service   #匹配后提供服务的路由地址  此处的lb是一个协议  Load Balanced
          predicates:
            - Path=/payment/queryPaymentById/**   #断言,路径相匹配的进行路由
            - After=2020-03-08T10:59:34.102+08:00[Asia/Shanghai]

        - id: payment_routh2
          uri: lb://cloud-payment-service
          predicates:
            #将uri和path拼凑起来： http://localhost:8001/payment/lb/** 将请求为../lb/下的所有请求拦截
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
#            - After=2020-03-08T10:59:34.102+08:00[Asia/Shanghai]  #在什么事件段之后
#            - Before=2020-09-08T10:59:34.102+08:00[Asia/Shanghai]
#            - Between=2020-03-08T10:59:34.102+08:00[Asia/Shanghai] ,  2020-09-08T10:59:34.102+08:00[Asia/Shanghai]
#            - Cookie=username,zs    #并且Cookie是username=zs才能访问
#            - Header=X-Request-Id, \d+   #请求头中要有X-Request-Id属性并且值为整数的正则表达式
#            - Query=username, \d+ #要有参数名称并且是正整数才能路由
            - Method=GET
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://eureka7001.com:7001/eureka